create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint profiles_username_format check (
    username is null or username ~ '^[A-Za-z0-9_-]{3,24}$'
  )
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null,
  body text,
  image_path text not null,
  thumb_path text,
  captured_at timestamptz,
  exact_lat double precision not null,
  exact_lng double precision not null,
  public_lat double precision not null,
  public_lng double precision not null,
  privacy_mode text not null default 'approx' check (privacy_mode in ('exact', 'approx')),
  place_name text,
  country_name text,
  region_name text,
  city_name text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_note text,
  approved_at timestamptz,
  approved_by uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint posts_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint posts_approved_by_fkey foreign key (approved_by) references public.profiles (id) on delete set null,
  constraint posts_title_length check (char_length(title) between 1 and 80),
  constraint posts_body_length check (body is null or char_length(body) <= 1000),
  constraint posts_exact_lat_range check (exact_lat between -90 and 90),
  constraint posts_exact_lng_range check (exact_lng between -180 and 180),
  constraint posts_public_lat_range check (public_lat between -90 and 90),
  constraint posts_public_lng_range check (public_lng between -180 and 180)
);

create index if not exists posts_status_created_at_idx
  on public.posts (status, created_at desc);

create index if not exists posts_public_point_idx
  on public.posts (public_lat, public_lng);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row
execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;

drop policy if exists "profiles_select_self" on public.profiles;
create policy "profiles_select_self"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "posts_select_approved" on public.posts;
create policy "posts_select_approved"
on public.posts
for select
to anon, authenticated
using (status = 'approved' or auth.uid() = user_id);

drop policy if exists "posts_insert_self" on public.posts;
create policy "posts_insert_self"
on public.posts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "posts_update_self" on public.posts;
create policy "posts_update_self"
on public.posts
for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status = 'pending');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fumo',
  'fumo',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "fumo_upload_own_folder" on storage.objects;
create policy "fumo_upload_own_folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "fumo_read_own_folder" on storage.objects;
create policy "fumo_read_own_folder"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "fumo_delete_own_folder" on storage.objects;
create policy "fumo_delete_own_folder"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- After running this schema, manually promote the first admin:
-- update public.profiles set role = 'admin' where username = 'your_admin_id';
