create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint profiles_username_format check (
    username is null or username ~ '^[A-Za-z0-9_-]{3,24}$'
  )
);

create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_en text not null unique,
  name_zh text,
  name_ja text,
  sort_order integer not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint characters_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint characters_name_en_length check (char_length(name_en) between 1 and 120),
  constraint characters_name_zh_length check (name_zh is null or char_length(name_zh) between 1 and 120),
  constraint characters_name_ja_length check (name_ja is null or char_length(name_ja) between 1 and 120),
  constraint characters_sort_order_nonnegative check (sort_order >= 0)
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null,
  body text,
  image_path text not null,
  thumb_path text,
  captured_at timestamptz,
  exact_lat double precision not null,
  exact_lng double precision not null,
  public_lat double precision not null,
  public_lng double precision not null,
  privacy_mode text not null default 'approx' check (privacy_mode in ('exact', 'approx')),
  place_name text,
  country_name text,
  region_name text,
  city_name text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_note text,
  approved_at timestamptz,
  approved_by uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint posts_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint posts_approved_by_fkey foreign key (approved_by) references public.profiles (id) on delete set null,
  constraint posts_title_length check (char_length(title) between 1 and 80),
  constraint posts_body_length check (body is null or char_length(body) <= 1000),
  constraint posts_exact_lat_range check (exact_lat between -90 and 90),
  constraint posts_exact_lng_range check (exact_lng between -180 and 180),
  constraint posts_public_lat_range check (public_lat between -90 and 90),
  constraint posts_public_lng_range check (public_lng between -180 and 180)
);

create table if not exists public.post_photos (
  post_id bigint not null references public.posts (id) on delete cascade,
  image_path text not null,
  thumb_path text,
  sort_order integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, sort_order),
  constraint post_photos_sort_order_range check (sort_order >= 0),
  constraint post_photos_image_path_unique unique (post_id, image_path)
);

create table if not exists public.post_characters (
  post_id bigint not null references public.posts (id) on delete cascade,
  character_id bigint not null references public.characters (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, character_id)
);

create table if not exists public.post_revisions (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  user_id uuid not null,
  title text not null,
  body text,
  image_path text not null,
  thumb_path text,
  captured_at timestamptz,
  exact_lat double precision not null,
  exact_lng double precision not null,
  public_lat double precision not null,
  public_lng double precision not null,
  privacy_mode text not null default 'approx' check (privacy_mode in ('exact', 'approx')),
  place_name text,
  country_name text,
  region_name text,
  city_name text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_note text,
  reviewed_at timestamptz,
  reviewed_by uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint post_revisions_post_id_fkey foreign key (post_id) references public.posts (id) on delete cascade,
  constraint post_revisions_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint post_revisions_reviewed_by_fkey foreign key (reviewed_by) references public.profiles (id) on delete set null,
  constraint post_revisions_title_length check (char_length(title) between 1 and 80),
  constraint post_revisions_body_length check (body is null or char_length(body) <= 1000),
  constraint post_revisions_exact_lat_range check (exact_lat between -90 and 90),
  constraint post_revisions_exact_lng_range check (exact_lng between -180 and 180),
  constraint post_revisions_public_lat_range check (public_lat between -90 and 90),
  constraint post_revisions_public_lng_range check (public_lng between -180 and 180)
);

create table if not exists public.post_revision_photos (
  revision_id bigint not null references public.post_revisions (id) on delete cascade,
  image_path text not null,
  thumb_path text,
  sort_order integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (revision_id, sort_order),
  constraint post_revision_photos_sort_order_range check (sort_order >= 0),
  constraint post_revision_photos_image_path_unique unique (revision_id, image_path)
);

create table if not exists public.post_revision_characters (
  revision_id bigint not null references public.post_revisions (id) on delete cascade,
  character_id bigint not null references public.characters (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (revision_id, character_id)
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, user_id)
);

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  content text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint suggestions_user_id_fkey
    foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint suggestions_content_length
    check (char_length(content) between 1 and 2000)
);

create index if not exists posts_status_created_at_idx
  on public.posts (status, created_at desc);

create index if not exists posts_public_point_idx
  on public.posts (public_lat, public_lng);

create index if not exists posts_approved_public_point_created_idx
  on public.posts (public_lat, public_lng, created_at desc)
  where status = 'approved';

create index if not exists post_photos_post_id_sort_order_idx
  on public.post_photos (post_id, sort_order);

create index if not exists post_characters_character_id_post_id_idx
  on public.post_characters (character_id, post_id);

create unique index if not exists post_revisions_one_pending_idx
  on public.post_revisions (post_id)
  where status = 'pending';

create index if not exists post_revisions_status_created_at_idx
  on public.post_revisions (status, created_at desc);

create index if not exists post_revision_photos_revision_id_sort_order_idx
  on public.post_revision_photos (revision_id, sort_order);

create index if not exists post_revision_characters_character_id_revision_id_idx
  on public.post_revision_characters (character_id, revision_id);

create index if not exists post_likes_user_id_created_at_idx
  on public.post_likes (user_id, created_at desc);

create index if not exists suggestions_created_at_idx
  on public.suggestions (created_at desc);

create or replace view public.public_profiles
with (security_barrier = true)
as
select
  id,
  username,
  avatar_url
from public.profiles
where username is not null;

create or replace view public.public_approved_posts
with (security_barrier = true)
as
select
  id,
  user_id,
  title,
  body,
  image_path,
  thumb_path,
  place_name,
  country_name,
  region_name,
  city_name,
  public_lat,
  public_lng,
  privacy_mode,
  captured_at,
  created_at,
  updated_at,
  status
from public.posts
where status = 'approved';

create or replace view public.public_approved_post_photos
with (security_barrier = true)
as
select
  post_photos.post_id,
  post_photos.image_path,
  post_photos.thumb_path,
  post_photos.sort_order,
  post_photos.created_at
from public.post_photos
join public.posts
  on posts.id = post_photos.post_id
where posts.status = 'approved';

create or replace view public.public_approved_post_like_counts
with (security_barrier = true)
as
select
  posts.id as post_id,
  count(post_likes.user_id)::integer as like_count
from public.posts
left join public.post_likes
  on post_likes.post_id = posts.id
where posts.status = 'approved'
group by posts.id;

create or replace view public.admin_character_backfill_posts
with (security_barrier = true)
as
select
  posts.id,
  posts.created_at
from public.posts
where posts.status = 'approved'
  and not exists (
    select 1
    from public.post_characters
    where post_characters.post_id = posts.id
  )
  and not exists (
    select 1
    from public.post_revisions
    where post_revisions.post_id = posts.id
      and post_revisions.status = 'pending'
  );

with character_seed (name_en, name_zh, name_ja, sort_order) as (
  select
    trim(seed_name_en),
    trim(seed_name_zh),
    trim(seed_name_ja),
    (ordinality - 1)::integer
  from unnest(array[
    'Hakurei Reimu',
    'Kirisame Marisa',
    'Shingyoku',
    'Mima',
    'Kikuri',
    'Konngara',
    'Yuugenmagan',
    'Elis',
    'Sariel',
    'Genjii',
    'Rika',
    'Meira',
    'Ellen',
    'Kotohime',
    'Kana Anaberal',
    'Asakura Rikako',
    'Kitashirakawa Chiyuri',
    'Okazaki Yumemi',
    'Mimi-chan',
    'Ruukoto',
    'Sokrates',
    'Orange',
    'Kurumi',
    'Elly',
    'Mugetsu',
    'Gengetsu',
    'Sara',
    'Louise',
    'Yuki',
    'Mai',
    'Yumeko',
    'Shinki',
    'Rumia',
    'Daiyousei',
    'Cirno',
    'Hong Meiling',
    'Koakuma',
    'Patchouli Knowledge',
    'Izayoi Sakuya',
    'Remilia Scarlet',
    'Flandre Scarlet',
    'Satsuki Rin',
    'Letty Whiterock',
    'Chen',
    'Alice Margatroid',
    'Lily White',
    'Lunasa Prismriver',
    'Merlin Prismriver',
    'Lyrica Prismriver',
    'Konpaku Youmu',
    'Saigyouji Yuyuko',
    'Yakumo Ran',
    'Yakumo Yukari',
    'Konpaku Youki',
    'Layla Prismriver',
    'Ibuki Suika',
    'Wriggle Nightbug',
    'Mystia Lorelei',
    'Kamishirasawa Keine',
    'Inaba Tewi',
    'Reisen Udongein Inaba',
    'Yagokoro Eirin',
    'Houraisan Kaguya',
    'Fujiwara no Mokou',
    'Medicine Melancholy',
    'Kazami Yuuka',
    'Onozuka Komachi',
    'Shiki Eiki',
    'Aki Shizuha',
    'Aki Minoriko',
    'Kagiyama Hina',
    'Kawashiro Nitori',
    'Inubashiri Momiji',
    'Kochiya Sanae',
    'Yasaka Kanako',
    'Moriya Suwako',
    'Nagae Iku',
    'Hinanawi Tenshi',
    'Kisume',
    'Kurodani Yamame',
    'Mizuhashi Parsee',
    'Hoshiguma Yuugi',
    'Komeiji Satori',
    'Kaenbyou Rin',
    'Reiuji Utsuho',
    'Komeiji Koishi',
    'Nazrin',
    'Tatara Kogasa',
    'Kumoi Ichirin',
    'Unzan',
    'Murasa Minamitsu',
    'Toramaru Shou',
    'Hijiri Byakuren',
    'Houjuu Nue',
    'Himekaidou Hatate',
    'Kasodani Kyouko',
    'Miyako Yoshika',
    'Kaku Seiga',
    'Soga no Tojiko',
    'Mononobe no Futo',
    'Toyosatomimi no Miko',
    'Futatsuiwa Mamizou',
    'Hata no Kokoro',
    'Wakasagihime',
    'Sekibanki',
    'Imaizumi Kagerou',
    'Tsukumo Benben',
    'Tsukumo Yatsuhashi',
    'Kijin Seija',
    'Sukuna Shinmyoumaru',
    'Horikawa Raiko',
    'Usami Sumireko',
    'Seiran',
    'Ringo',
    'Doremy Sweet',
    'Kishin Sagume',
    'Clownpiece',
    'Junko',
    'Hecatia Lapislazuli',
    'Yorigami Jo''on',
    'Yorigami Shion',
    'Eternity Larva',
    'Sakata Nemuno',
    'Komano Aunn',
    'Yatadera Narumi',
    'Nishida Satono',
    'Teireida Mai',
    'Matara Okina',
    'Ebisu Eika',
    'Ushizaki Urumi',
    'Niwatari Kutaka',
    'Kicchou Yachie',
    'Joutouguu Mayumi',
    'Haniyasushin Keiki',
    'Kurokoma Saki',
    'Toutetsu Yuuma',
    'Goutokuji Mike',
    'Yamashiro Takane',
    'Komakusa Sannyo',
    'Tamatsukuri Misumaru',
    'Kudamaki Tsukasa',
    'Iizunamaru Megumu',
    'Tenkyuu Chimata',
    'Himemushi Momoyo',
    'Son Biten',
    'Mitsugashira Enoko',
    'Tenkajin Chiyari',
    'Yomotsu Hisami',
    'Nippaku Zanmu',
    'Chirizuka Ubame',
    'Houjuu Chimi',
    'Michigami Nareko',
    'Yuiman Asama',
    'Iwanaga Ariya',
    'Watari Nina',
    'Morichika Rinnosuke',
    'Tokiko',
    'Shameimaru Aya',
    'Sunny Milk',
    'Luna Child',
    'Star Sapphire',
    'Watatsuki no Toyohime',
    'Watatsuki no Yorihime',
    'Reisen_(Bougetsushou)',
    'Hieda no Akyuu',
    'Ibaraki Kasen',
    'Motoori Kosuzu',
    'Miyadeguchi Mizuchi',
    'Okunoda Miyoi',
    'Usami Renko',
    'Maribel Hearn',
    'Labelko',
    'Jacketko'
  ], array[
    '博丽灵梦',
    '雾雨魔理沙',
    '神玉',
    '魅魔',
    '菊理',
    '矜羯罗',
    '幽幻魔眼',
    '依莉斯',
    '萨丽爱尔',
    '玄爷',
    '里香',
    '明罗',
    '爱莲',
    '小兔姬',
    '卡娜·安娜贝拉尔',
    '朝仓理香子',
    '北白河千百合',
    '冈崎梦美',
    '咪咪号',
    '留琴',
    '苏格拉底',
    '奥莲姬',
    '胡桃',
    '艾丽',
    '梦月',
    '幻月',
    '萨拉',
    '露易兹',
    '雪',
    '舞',
    '梦子',
    '神绮',
    '露米娅',
    '大妖精',
    '琪露诺',
    '红美铃',
    '小恶魔',
    '帕秋莉·诺蕾姬',
    '十六夜咲夜',
    '蕾米莉亚·斯卡蕾特',
    '芙兰朵露·斯卡蕾特',
    '冴月麟',
    '蕾蒂·霍瓦特洛克',
    '橙',
    '爱丽丝·玛格特洛依德',
    '莉莉霍瓦特',
    '露娜萨·普莉兹姆利巴',
    '梅露兰·普莉兹姆利巴',
    '莉莉卡·普莉兹姆利巴',
    '魂魄妖梦',
    '西行寺幽幽子',
    '八云蓝',
    '八云紫',
    '魂魄妖忌',
    '蕾拉·普莉兹姆利巴',
    '伊吹萃香',
    '莉格露·奈特巴格',
    '米斯蒂娅·萝蕾拉',
    '上白泽慧音',
    '因幡天为',
    '铃仙·优昙华院·因幡',
    '八意永琳',
    '蓬莱山辉夜',
    '藤原妹红',
    '梅蒂欣·梅兰可莉',
    '风见幽香',
    '小野塚小町',
    '四季映姬·夜摩仙那度',
    '秋静叶',
    '秋穰子',
    '键山雏',
    '河城荷取',
    '犬走椛',
    '东风谷早苗',
    '八坂神奈子',
    '洩矢诹访子',
    '永江衣玖',
    '比那名居天子',
    '大鲶鱼',
    '琪斯美',
    '黑谷山女',
    '水桥帕露西',
    '星熊勇仪',
    '古明地觉',
    '火焰猫燐',
    '灵乌路空',
    '古明地恋',
    '娜兹玲',
    '多多良小伞',
    '云居一轮&云山',
    '村纱水蜜',
    '寅丸星',
    '圣白莲',
    '封兽鵺',
    '姬海棠果',
    '幽谷响子',
    '宫古芳香',
    '霍青娥',
    '苏我屠自古',
    '物部布都',
    '丰聪耳神子',
    '二岩猯藏',
    '秦心',
    '若鹭姬',
    '赤蛮奇',
    '今泉影狼',
    '九十九弁弁',
    '九十九八桥',
    '鬼人正邪',
    '少名针妙丸',
    '堀川雷鼓',
    '宇佐见堇子',
    '清兰',
    '铃瑚',
    '哆来咪·苏伊特',
    '稀神探女',
    '克劳恩皮丝',
    '纯狐',
    '赫卡提亚·拉碧斯拉祖利',
    '依神女苑',
    '依神紫苑',
    '爱塔妮缇拉尔瓦',
    '坂田合欢',
    '高丽野阿吽',
    '矢田寺成美',
    '尔子田里乃',
    '丁礼田舞',
    '摩多罗隐岐奈',
    '戎璎花',
    '牛崎润美',
    '庭渡久侘歌',
    '吉吊八千慧',
    '杖刀偶磨弓',
    '埴安神袿姬',
    '骊驹早鬼',
    '饕餮尤魔',
    '豪德寺三花',
    '山城高岭',
    '驹草山如',
    '玉造魅须丸',
    '菅牧典',
    '饭纲丸龙',
    '天弓千亦',
    '姬虫百百世',
    '孙美天',
    '三头慧之子',
    '天火人血枪',
    '豫母都日狭美',
    '日白残无',
    '尘塚姥芽',
    '封兽魑魅',
    '道神驯子',
    '维缦·浅间',
    '磐永阿梨夜',
    '渡里贝子',
    '森近霖之助',
    '无名的读书妖怪',
    '射命丸文',
    '桑尼米尔克',
    '露娜切露德',
    '斯塔萨菲雅',
    '绵月丰姬',
    '绵月依姬',
    'Reisen',
    '稗田阿求',
    '茨木华扇',
    '本居小铃',
    '宫出口瑞灵',
    '奥野田美宵',
    '宇佐见莲子',
    '玛艾露贝莉·赫恩',
    'Label子',
    '夹克子'
  ], array[
    '博麗　霊夢',
    '霧雨　魔理沙',
    'しんぎょく',
    '魅魔',
    'きくり',
    '矜羯羅',
    'ゆうげんまがん',
    'エリス',
    'サリエル',
    '玄爺',
    '里香',
    '明羅',
    'エレン',
    '小兎姫',
    'カナ・アナベラル',
    '朝倉　理香子',
    '北白河　ちゆり',
    '岡崎　夢美',
    'ミミちゃん',
    'る～こと',
    'ソクラテス',
    'オレンジ',
    'くるみ',
    'エリー',
    '夢月',
    '幻月',
    'サラ',
    'ルイズ',
    'ユキ',
    'マイ',
    '夢子',
    '神綺',
    'ルーミア',
    '大妖精',
    'チルノ',
    '紅　美鈴',
    '小悪魔',
    'パチュリー・ノーレッジ',
    '十六夜　咲夜',
    'レミリア・スカーレット',
    'フランドール・スカーレット',
    '冴月　麟',
    'レティ・ホワイトロック',
    '橙',
    'アリス・マーガトロイド',
    'リリーホワイト',
    'ルナサ・プリズムリバー',
    'メルラン・プリズムリバー',
    'リリカ・プリズムリバー',
    '魂魄　妖夢',
    '西行寺　幽々子',
    '八雲　藍',
    '八雲　紫',
    '魂魄　妖忌',
    'レイラ・プリズムリバー',
    '伊吹　萃香',
    'リグル・ナイトバグ',
    'ミスティア・ローレライ',
    '上白沢　慧音',
    '因幡　てゐ',
    '鈴仙・優曇華院・イナバ',
    '八意　永琳',
    '蓬莱山　輝夜',
    '藤原　妹紅',
    'メディスン・メランコリー',
    '風見　幽香',
    '小野塚　小町',
    '四季映姫・ヤマザナドゥ',
    '秋　静葉',
    '秋　穣子',
    '鍵山　雛',
    '河城　にとり',
    '犬走　椛',
    '東風谷　早苗',
    '八坂　神奈子',
    '洩矢　諏訪子',
    '永江　衣玖',
    '比那名居　天子',
    '大ナマズ',
    'キスメ',
    '黒谷　ヤマメ',
    '水橋　パルスィ',
    '星熊　勇儀',
    '古明地　さとり',
    '火焔猫　燐',
    '霊烏路　空',
    '古明地　こいし',
    'ナズーリン',
    '多々良　小傘',
    '雲居　一輪 & 雲山',
    '村紗　水蜜',
    '寅丸　星',
    '聖　白蓮',
    '封獣　ぬえ',
    '姫海棠　はたて',
    '幽谷　響子',
    '宮古　芳香',
    '霍　青娥',
    '蘇我　屠自古',
    '物部　布都',
    '豊聡耳　神子',
    '二ッ岩　マミゾウ',
    '秦　こころ',
    'わかさぎ姫',
    '赤蛮奇',
    '今泉　影狼',
    '九十九　弁々',
    '九十九　八橋',
    '鬼人　正邪',
    '少名　針妙丸',
    '堀川　雷鼓',
    '宇佐見　菫子',
    '清蘭',
    '鈴瑚',
    'ドレミー・スイート',
    '稀神　サグメ',
    'クラウンピース',
    '純狐',
    'ヘカーティア・ラピスラズリ',
    '依神 女苑',
    '依神 紫苑',
    'エタニティラルバ',
    '坂田　ネムノ',
    '高麗野　あうん',
    '矢田寺　成美',
    '爾子田　里乃',
    '丁礼田　舞',
    '摩多羅　隠岐奈',
    '戎　瓔花',
    '牛崎　潤美',
    '庭渡　久侘歌',
    '吉弔　八千慧',
    '杖刀偶　磨弓',
    '埴安神　袿姫',
    '驪駒　早鬼',
    '饕餮　尤魔',
    '豪徳寺　ミケ',
    '山城　たかね',
    '駒草　山如',
    '玉造　魅須丸',
    '菅牧　典',
    '飯綱丸 龍',
    '天弓　千亦',
    '姫虫　百々世',
    '孫　美天',
    '三頭 慧ノ子',
    '天火人 ちやり',
    '豫母都　日狭美',
    '日白　残無',
    '塵塚　ウバメ',
    '封獣　チミ',
    '道神　馴子',
    'ユイマン・浅間',
    '磐永 阿梨夜',
    '渡里 ニナ',
    '森近　霖之助',
    '名無しの本読み妖怪',
    '射命丸　文',
    'サニーミルク',
    'ルナチャイルド',
    'スターサファイア',
    '綿月　豊姫',
    '綿月　依姫',
    'レイセン',
    '稗田　阿求',
    '茨木　華扇',
    '本居　小鈴',
    '宮出口　瑞霊',
    '奥野田　美宵',
    '宇佐見　蓮子',
    'マエリベリー・ハーン',
    'レーベルイラストの娘',
    'ジャケットイラストの娘'
  ]) with ordinality as seed(seed_name_en, seed_name_zh, seed_name_ja, ordinality)
)
insert into public.characters (slug, name_en, name_zh, name_ja, sort_order)
select
  trim(both '-' from regexp_replace(lower(name_en), '[^a-z0-9]+', '-', 'g')),
  name_en,
  name_zh,
  name_ja,
  sort_order
from character_seed
on conflict (name_en) do update
set
  slug = excluded.slug,
  name_zh = excluded.name_zh,
  name_ja = excluded.name_ja,
  sort_order = excluded.sort_order;

create or replace function public.get_public_map_posts(
  requested_character_slugs text[] default '{}'::text[]
)
returns table (
  id bigint,
  public_lat double precision,
  public_lng double precision
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    public_approved_posts.id,
    public_approved_posts.public_lat,
    public_approved_posts.public_lng
  from public.public_approved_posts
  where public_approved_posts.public_lat is not null
    and public_approved_posts.public_lng is not null
    and (
      coalesce(array_length(requested_character_slugs, 1), 0) = 0
      or exists (
        select 1
        from public.post_characters
        join public.characters
          on characters.id = post_characters.character_id
        where post_characters.post_id = public_approved_posts.id
          and characters.slug = any(requested_character_slugs)
      )
    )
  order by public_approved_posts.id;
$$;

insert into public.post_photos (post_id, image_path, thumb_path, sort_order, created_at)
select id, image_path, thumb_path, 0, created_at
from public.posts
where image_path is not null
on conflict (post_id, sort_order) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_characters_updated_at on public.characters;
create trigger set_characters_updated_at
before update on public.characters
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_post_revisions_updated_at on public.post_revisions;
create trigger set_post_revisions_updated_at
before update on public.post_revisions
for each row
execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.characters enable row level security;
alter table public.posts enable row level security;
alter table public.post_photos enable row level security;
alter table public.post_characters enable row level security;
alter table public.post_revisions enable row level security;
alter table public.post_revision_photos enable row level security;
alter table public.post_revision_characters enable row level security;
alter table public.post_likes enable row level security;
alter table public.suggestions enable row level security;

revoke all on public.profiles, public.characters, public.posts, public.post_photos, public.post_characters, public.post_revisions, public.post_revision_photos, public.post_revision_characters, public.post_likes, public.suggestions
  from public, anon, authenticated;
revoke all on public.public_profiles, public.public_approved_posts, public.public_approved_post_photos, public.public_approved_post_like_counts
  from public, anon, authenticated;
revoke all on public.admin_character_backfill_posts
  from public, anon, authenticated;
revoke all on function public.get_public_map_posts(text[])
  from public;

grant select on public.public_profiles, public.public_approved_posts, public.public_approved_post_photos, public.public_approved_post_like_counts
  to anon, authenticated;
grant select on public.admin_character_backfill_posts to service_role;
grant execute on function public.get_public_map_posts(text[]) to anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.characters to anon, authenticated;
revoke insert (id, username, avatar_url, role, created_at, updated_at)
  on public.profiles from anon, authenticated;
revoke update (id, username, avatar_url, role, created_at, updated_at)
  on public.profiles from anon, authenticated;
grant insert (id, username, avatar_url) on public.profiles to authenticated;
grant update (username, avatar_url) on public.profiles to authenticated;

grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, delete on public.post_photos to authenticated;
grant select on public.post_characters to anon, authenticated;
grant insert, delete on public.post_characters to authenticated;
grant select, insert, update, delete on public.post_revisions to authenticated;
grant select, insert, delete on public.post_revision_photos to authenticated;
grant select, insert, delete on public.post_revision_characters to authenticated;
grant select, insert, delete on public.post_likes to authenticated;
grant insert on public.suggestions to authenticated;

drop policy if exists "characters_select_public" on public.characters;
create policy "characters_select_public"
on public.characters
for select
to anon, authenticated
using (true);

drop policy if exists "profiles_select_self" on public.profiles;
create policy "profiles_select_self"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id and role = 'user');

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "posts_select_approved" on public.posts;
drop policy if exists "posts_select_self" on public.posts;
create policy "posts_select_self"
on public.posts
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "posts_insert_self" on public.posts;
create policy "posts_insert_self"
on public.posts
for insert
to authenticated
with check (auth.uid() = user_id and status = 'pending');

drop policy if exists "posts_update_self" on public.posts;
create policy "posts_update_self"
on public.posts
for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status = 'pending');

drop policy if exists "posts_delete_self_pending" on public.posts;
create policy "posts_delete_self_pending"
on public.posts
for delete
to authenticated
using (auth.uid() = user_id and status = 'pending');

drop policy if exists "post_photos_select_visible" on public.post_photos;
drop policy if exists "post_photos_select_self" on public.post_photos;
create policy "post_photos_select_self"
on public.post_photos
for select
to authenticated
using (
  exists (
    select 1
    from public.posts
    where posts.id = post_photos.post_id
      and posts.user_id = auth.uid()
  )
);

drop policy if exists "post_photos_insert_self" on public.post_photos;
create policy "post_photos_insert_self"
on public.post_photos
for insert
to authenticated
with check (
  exists (
    select 1
    from public.posts
    where posts.id = post_photos.post_id
      and posts.user_id = auth.uid()
      and posts.status = 'pending'
  )
);

drop policy if exists "post_photos_delete_self_pending" on public.post_photos;
create policy "post_photos_delete_self_pending"
on public.post_photos
for delete
to authenticated
using (
  exists (
    select 1
    from public.posts
    where posts.id = post_photos.post_id
      and posts.user_id = auth.uid()
      and posts.status = 'pending'
  )
);

drop policy if exists "post_characters_select_approved" on public.post_characters;
create policy "post_characters_select_approved"
on public.post_characters
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.public_approved_posts
    where public_approved_posts.id = post_characters.post_id
  )
);

drop policy if exists "post_characters_select_self" on public.post_characters;
create policy "post_characters_select_self"
on public.post_characters
for select
to authenticated
using (
  exists (
    select 1
    from public.posts
    where posts.id = post_characters.post_id
      and posts.user_id = (select auth.uid())
  )
);

drop policy if exists "post_characters_insert_self" on public.post_characters;
create policy "post_characters_insert_self"
on public.post_characters
for insert
to authenticated
with check (
  exists (
    select 1
    from public.posts
    where posts.id = post_characters.post_id
      and posts.user_id = (select auth.uid())
      and posts.status = 'pending'
  )
);

drop policy if exists "post_characters_delete_self_pending" on public.post_characters;
create policy "post_characters_delete_self_pending"
on public.post_characters
for delete
to authenticated
using (
  exists (
    select 1
    from public.posts
    where posts.id = post_characters.post_id
      and posts.user_id = (select auth.uid())
      and posts.status = 'pending'
  )
);

drop policy if exists "post_revisions_select_self" on public.post_revisions;
create policy "post_revisions_select_self"
on public.post_revisions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "post_revisions_insert_self" on public.post_revisions;
create policy "post_revisions_insert_self"
on public.post_revisions
for insert
to authenticated
with check (
  auth.uid() = user_id
  and status = 'pending'
  and exists (
    select 1
    from public.posts
    where posts.id = post_revisions.post_id
      and posts.user_id = auth.uid()
      and posts.status = 'approved'
  )
);

drop policy if exists "post_revisions_update_self" on public.post_revisions;
create policy "post_revisions_update_self"
on public.post_revisions
for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (
  auth.uid() = user_id
  and status = 'pending'
  and exists (
    select 1
    from public.posts
    where posts.id = post_revisions.post_id
      and posts.user_id = auth.uid()
      and posts.status = 'approved'
  )
);

drop policy if exists "post_revisions_delete_self_pending" on public.post_revisions;
create policy "post_revisions_delete_self_pending"
on public.post_revisions
for delete
to authenticated
using (auth.uid() = user_id and status = 'pending');

drop policy if exists "post_revision_photos_select_self" on public.post_revision_photos;
create policy "post_revision_photos_select_self"
on public.post_revision_photos
for select
to authenticated
using (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_photos.revision_id
      and post_revisions.user_id = auth.uid()
  )
);

drop policy if exists "post_revision_photos_insert_self" on public.post_revision_photos;
create policy "post_revision_photos_insert_self"
on public.post_revision_photos
for insert
to authenticated
with check (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_photos.revision_id
      and post_revisions.user_id = auth.uid()
      and post_revisions.status = 'pending'
  )
);

drop policy if exists "post_revision_photos_delete_self_pending" on public.post_revision_photos;
create policy "post_revision_photos_delete_self_pending"
on public.post_revision_photos
for delete
to authenticated
using (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_photos.revision_id
      and post_revisions.user_id = auth.uid()
      and post_revisions.status = 'pending'
  )
);

drop policy if exists "post_revision_characters_select_self" on public.post_revision_characters;
create policy "post_revision_characters_select_self"
on public.post_revision_characters
for select
to authenticated
using (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_characters.revision_id
      and post_revisions.user_id = (select auth.uid())
  )
);

drop policy if exists "post_revision_characters_insert_self" on public.post_revision_characters;
create policy "post_revision_characters_insert_self"
on public.post_revision_characters
for insert
to authenticated
with check (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_characters.revision_id
      and post_revisions.user_id = (select auth.uid())
      and post_revisions.status = 'pending'
  )
);

drop policy if exists "post_revision_characters_delete_self_pending" on public.post_revision_characters;
create policy "post_revision_characters_delete_self_pending"
on public.post_revision_characters
for delete
to authenticated
using (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_characters.revision_id
      and post_revisions.user_id = (select auth.uid())
      and post_revisions.status = 'pending'
  )
);

drop policy if exists "post_likes_select_self" on public.post_likes;
create policy "post_likes_select_self"
on public.post_likes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "post_likes_insert_self_approved" on public.post_likes;
create policy "post_likes_insert_self_approved"
on public.post_likes
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.public_approved_posts
    where public_approved_posts.id = post_likes.post_id
  )
);

drop policy if exists "post_likes_delete_self" on public.post_likes;
create policy "post_likes_delete_self"
on public.post_likes
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "suggestions_insert_self" on public.suggestions;
create policy "suggestions_insert_self"
on public.suggestions
for insert
to authenticated
with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fumo',
  'fumo',
  false,
  20971520,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "fumo_upload_own_folder" on storage.objects;
create policy "fumo_upload_own_folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "fumo_read_own_folder" on storage.objects;
create policy "fumo_read_own_folder"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "fumo_delete_own_folder" on storage.objects;
create policy "fumo_delete_own_folder"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- After running this schema, manually promote the first admin:
-- update public.profiles set role = 'admin' where username = 'your_admin_id';
